(entra-utilizador 'administrador)
ip-admin
(inserir-categoria 'electronica 'musica 'livros)
(inserir-categoria)
(categorias-disponiveis)
(inserir-categoria 'viagens 'musica)
(categorias-disponiveis)
(remover-categoria 'electronica)
(categorias-disponiveis)
(remover-categoria 'mobiliario)
(categorias-disponiveis)
(inicia-tempo 2002 10 6 18 35)
(visualiza-tempo)
(sair)
(entrar)
(regista 'maria "Maria Ninguém" "Rua de Cima, 12 - 3º, 5500-005 Lugar de Baixo, Portugal" "maria@mega.ist.utl.pt" 'mariazinha)
(sair)
(entra-utilizador 'maria)
mariazinha
(dados-utilizador 'maria)
(nome "Maria Alguém")
(morada "Rua de Baixo, 12 - 3º, 5005-500 Lugar de Cima, Portugal")
(dados-utilizador 'maria)
(cria-produto 'viagem-Haiti "Viagem de sonho ao Haiti" 'viagens 1000 (cria-tempo (cria-data 2002 10 13) (cria-hora 10 00)))
(dados-produto 'viagem-Haiti)
(sair)
(entrar)
(regista 'ze "José Ninguém" "Rua de Cima, 12 - 3º, 5500-005 Lugar de Baixo, Portugal" "zeninguem@mega.ist.utl.pt" 'secreta)
(regista 'ze "José Ninguém" "Rua de Cima, 12 - 3º, 5500-005 Lugar de Baixo, Portugal" "zeninguem@mega.ist.utl.pt" 'secreta)
(sair)
(entra-utilizador 'ze)
secreta
(passa-tempo 612)
(visualiza-tempo) 
(dados-utilizador 'maria)
(categorias-disponiveis)
(cria-produto 'folhas-ip "Livro de suporte à cadeira de IP" 'livros 5 (cria-tempo (cria-data 2002 10 13) (cria-hora 12 30)))
(dados-produto 'folhas-ip)
(cria-produto 'folhas-ip "Folhas da cadeira de IP" 'livros 6.20 (cria-tempo (cria-data 2002 10 11) (cria-hora 12 00)))
(dados-produto 'folhas-amI)
(licita 'viagem-Haiti 1050)
(passa-tempo 1000)
(visualiza-tempo) 
(sair)
(entrar)
(regista 'manel "Manel Manuel" "Rua Direita, 23 - 1º, 4200-050 Lugar 
Torto, Portugal" "manelmanuel@mega.ist.utl.pt" 'manelito)
(sair)
(entra-utilizador 'manel)
manelito
(cria-produto 'cd-Natal "Pavarotti canta o Natal" 'musica 10 (cria-tempo (cria-data 2002 10 12) (cria-hora 15 00)))
(dados-produto 'cd-Natal)
(cria-produto 'cd-PearlJam "Ten" 'musica 15 (cria-tempo (cria-data 2002 10 10) (cria-hora 16 30)))
(licita 'folhas-ip 7.50)
(licita 'viagem-Haiti 1100)
(licita 'cd-U2 20)
(processo-produto 'folhas-ip)
(processo-produto 'viagem-Haiti)
(processo-produto 'cd-PearlJam)
(sair)
(entra-utilizador 'maria)
mariazinha
(passa-tempo 4320)
(visualiza-tempo) 
(processo-produto 'cd-PearlJam)
(licita 'cd-Natal 11)
(licita 'folhas-ip 8)
(processo-produto 'folhas-ip)
(sair)
(entra-utilizador 'ze)
secreta
(licita 'cd-Natal 12)
(passa-tempo 3660)
(visualiza-tempo) 
(licita 'cd-PearlJam 20)
(sair)
(entra-utilizador 'manel)
manelito
(processo-utilizador 'maria)
(processo-utilizador 'ze)
(utilizadores-registados)
(produtos-em-licitacao)
(produtos-em-licitacao 'livros)
(produtos-vendidos)
(produtos-nao-vendidos)
(sair) 
(entra-utilizador 'ze)
secreta
(sair)
(entra-utilizador 'maria)
mariazinha
(sair)
(entra-utilizador 'manel)
manelito
(sair)
(terminar-ip-Bay)
